import type { Locale } from '../i18n/locales';
import { pick, type Localized } from './localize';

// Alt text of each photo, written once and reused wherever the photo appears.
const FR: Record<string, string> = {
  'craves-hotel-bruxelles-chambre-velours-bleu': 'Chambre du Craves Hotel à Bruxelles : tête de lit en velours bleu, coussin rond et miroir ovale',
  'chambres-craves-hotel-bruxelles': 'Chambre du Craves Hotel avec papier peint floral, tête de lit en velours bleu et ventilateur au plafond',
  'chambre-simple-craves-bruxelles': 'Chambre simple du Craves Hotel avec lit simple, velours bleu et papier peint floral',
  'chambre-simple-craves-bruxelles-2': 'Chambre simple du Craves Hotel, vue vers la porte et la tête de lit',
  'chambre-simple-craves-salle-de-bains': 'Salle de bains de la chambre simple avec douche',
  'chambre-double-craves-bruxelles': 'Chambre double du Craves Hotel : lit, tête de lit en velours bleu et papier peint floral',
  'chambre-double-craves-bruxelles-2': 'Chambre double du Craves Hotel : grand lit, tête de lit en velours bleu et papier peint floral',
  'chambre-double-craves-detail': 'Coiffeuse, cadres anciens et pouf rouge dans la chambre double',
  'chambre-double-craves-salle-de-bains': 'Salle de bains de la chambre double avec baignoire et double vasque',
  'chambre-triple-craves-lit-double-et-simple': 'Chambre triple du Craves Hotel avec un lit double et un lit simple',
  'chambre-triple-craves-banquette': 'Banquette et pouf rouge dans la chambre triple',
  'chambre-triple-craves-service-the': 'Service à thé en porcelaine sur le marbre de la chambre triple',
  'chambre-famille-craves-bruxelles': 'Chambre famille du Craves Hotel avec salon et canapé-lit',
  'chambre-famille-craves-portrait': 'Chambre famille du Craves Hotel avec coin repas et salon',
  'chambre-famille-craves-chambre': 'Lits de la chambre famille, papier peint floral et tête de lit en velours',
  'chambre-famille-craves-coin-repas': 'Kitchenette et coin repas de la chambre famille',
  'le-conteur-bar-restaurant-craves': 'Le bar du restaurant Le Conteur, tabourets orange et étagères de bouteilles',
  'le-conteur-restaurant-craves-bruxelles': 'Convives qui trinquent autour de mezze au restaurant Le Conteur',
  'le-conteur-pain-tresse-mezze': 'Pain tressé au sésame et mezze à partager au Conteur',
  'le-conteur-cocktail-barman': 'Barman du Conteur qui verse un cocktail aux baies',
  'le-conteur-poisson-grille': 'Poisson grillé servi dans une assiette en faïence bleue',
  'le-conteur-applique-laiton': 'Applique en laiton sur le carrelage blanc du Conteur',
  'le-conteur-diner-festif': 'Convives qui trinquent au vin rouge autour d’une table du Conteur',
  'le-conteur-cocktail-ambre': 'Cocktail ambré au citron séché et à la cannelle',
  'scene-bar-craves-bruxelles': 'Le comptoir lumineux du bar Scène, au niveau Atrium du Craves',
  'scene-bar-enseigne-leopard': 'Enseigne Scène sur fond léopard, lumière rouge',
  'scene-bar-cocktail-flambe': 'Cocktail flambé servi dans une tête de mort colorée au bar Scène',
  'scene-bar-dj-soiree': 'Soirée DJ au bar Scène',
  'scene-bar-neon': 'Néon rouge à l’entrée du bar Scène',
  'scene-bar-lustres-soiree': 'Salle de Scène sous les lustres, soirée privée',
  'craves-reception-hall': 'La réception du Craves Hotel, bois et lumière chaude',
  'craves-reception-accueil': 'La réception du Craves Hotel, comptoir en bois et fauteuil rouge',
  'craves-couloir-moquette-florale': 'Couloir du Craves Hotel, boiseries sombres et moquette florale',
  'craves-couloir-bleu': 'Couloir bleu du Craves Hotel',
  'craves-papier-peint-floral': 'Papier peint floral inspiré des cinq sens',
  'craves-papier-peint-floral-2': 'Papier peint floral du Craves',
  'craves-rideau-velours-embrasse-or': 'Rideau de velours bleu à embrasse dorée',
  'craves-applique-lumiere': 'Applique en verre ciselé et lumière chaude',
  'craves-telephone-retro': 'Téléphone rétro sur le marbre d’une chambre',
  'craves-tapis-motif': 'Tapis à motifs sur parquet',
  'craves-cocktail-marbre': 'Coupe de cocktail rose sur le marbre',
  'palais-royal-bruxelles': 'Le Palais royal de Bruxelles',
  'grand-place-bruxelles-crepuscule': 'La Grand-Place de Bruxelles au crépuscule, à 4 minutes à pied du Craves Hotel',
  'grand-place-bruxelles-hotel-de-ville': 'L’Hôtel de Ville sur la Grand-Place de Bruxelles, à 4 minutes à pied du Craves',
  'manneken-pis-bruxelles': 'La statue du Manneken-Pis à Bruxelles',
  'palais-de-justice-bruxelles': 'Colonnes du Palais de Justice de Bruxelles',
  'plaisirs-d-hiver-grande-roue-bruxelles': 'La grande roue illuminée des Plaisirs d’Hiver à Bruxelles',
  'plaisirs-d-hiver-eglise-sainte-catherine': 'L’église Sainte-Catherine illuminée pendant les Plaisirs d’Hiver',
  'sapin-de-noel-grand-place-bruxelles': 'Le sapin de Noël illuminé devant l’Hôtel de Ville, sur la Grand-Place de Bruxelles',
  'gare-bruxelles-midi-quai-train': 'Un train à grande vitesse à quai à la gare de Bruxelles-Midi',
};

const EN: Record<string, string> = {
  'craves-hotel-bruxelles-chambre-velours-bleu': 'Room at Craves Hotel in Brussels: blue velvet headboard, round cushion and oval mirror',
  'chambres-craves-hotel-bruxelles': 'Craves Hotel room with floral wallpaper, blue velvet headboard and ceiling fan',
  'chambre-simple-craves-bruxelles': 'Single room at Craves Hotel with single bed, blue velvet and floral wallpaper',
  'chambre-simple-craves-bruxelles-2': 'Single room at Craves Hotel, looking towards the door and the headboard',
  'chambre-simple-craves-salle-de-bains': 'Single room bathroom with shower',
  'chambre-double-craves-bruxelles': 'Double room at Craves Hotel: bed, blue velvet headboard and floral wallpaper',
  'chambre-double-craves-bruxelles-2': 'Double room at Craves Hotel: large bed, blue velvet headboard and floral wallpaper',
  'chambre-double-craves-detail': 'Dressing table, vintage frames and red pouffe in the double room',
  'chambre-double-craves-salle-de-bains': 'Double room bathroom with bathtub and double washbasin',
  'chambre-triple-craves-lit-double-et-simple': 'Triple room at Craves Hotel with a double bed and a single bed',
  'chambre-triple-craves-banquette': 'Banquette and red pouffe in the triple room',
  'chambre-triple-craves-service-the': 'Porcelain tea set on the marble in the triple room',
  'chambre-famille-craves-bruxelles': 'Family room at Craves Hotel with lounge area and sofa bed',
  'chambre-famille-craves-portrait': 'Family room at Craves Hotel with dining area and lounge',
  'chambre-famille-craves-chambre': 'Beds in the family room, floral wallpaper and velvet headboard',
  'chambre-famille-craves-coin-repas': 'Kitchenette and dining area in the family room',
  'le-conteur-bar-restaurant-craves': 'The bar at Le Conteur restaurant, orange stools and shelves of bottles',
  'le-conteur-restaurant-craves-bruxelles': 'Guests raising a toast over mezze at Le Conteur restaurant',
  'le-conteur-pain-tresse-mezze': 'Braided sesame bread and mezze to share at Le Conteur',
  'le-conteur-cocktail-barman': 'Le Conteur bartender pouring a berry cocktail',
  'le-conteur-poisson-grille': 'Grilled fish served on a blue earthenware plate',
  'le-conteur-applique-laiton': 'Brass wall light on the white tiles of Le Conteur',
  'le-conteur-diner-festif': 'Guests toasting with red wine around a table at Le Conteur',
  'le-conteur-cocktail-ambre': 'Amber cocktail with dried lemon and cinnamon',
  'scene-bar-craves-bruxelles': 'The illuminated counter of the Scène bar, on the Atrium level of Craves',
  'scene-bar-enseigne-leopard': 'Scène sign on a leopard-print background, red light',
  'scene-bar-cocktail-flambe': 'Flaming cocktail served in a colourful skull at the Scène bar',
  'scene-bar-dj-soiree': 'DJ night at the Scène bar',
  'scene-bar-neon': 'Red neon sign at the entrance to the Scène bar',
  'scene-bar-lustres-soiree': 'The Scène room beneath the chandeliers, private party',
  'craves-reception-hall': 'Craves Hotel reception, wood and warm light',
  'craves-reception-accueil': 'Craves Hotel reception, wooden desk and red armchair',
  'craves-couloir-moquette-florale': 'Craves Hotel corridor, dark wood panelling and floral carpet',
  'craves-couloir-bleu': 'Blue corridor at Craves Hotel',
  'craves-papier-peint-floral': 'Floral wallpaper inspired by the five senses',
  'craves-papier-peint-floral-2': 'Craves floral wallpaper',
  'craves-rideau-velours-embrasse-or': 'Blue velvet curtain with a gold tieback',
  'craves-applique-lumiere': 'Cut-glass wall light and warm light',
  'craves-telephone-retro': 'Retro telephone on the marble in a room',
  'craves-tapis-motif': 'Patterned rug on parquet flooring',
  'craves-cocktail-marbre': 'Pink cocktail coupe on marble',
  'palais-royal-bruxelles': 'The Royal Palace of Brussels',
  'grand-place-bruxelles-crepuscule': 'The Grand-Place in Brussels at dusk, a 4-minute walk from Craves Hotel',
  'grand-place-bruxelles-hotel-de-ville': 'The Town Hall on the Grand-Place in Brussels, a 4-minute walk from Craves',
  'manneken-pis-bruxelles': 'The Manneken Pis statue in Brussels',
  'palais-de-justice-bruxelles': 'Columns of the Palace of Justice in Brussels',
  'plaisirs-d-hiver-grande-roue-bruxelles': 'The illuminated Ferris wheel of Winter Wonders in Brussels',
  'plaisirs-d-hiver-eglise-sainte-catherine': 'Saint Catherine’s Church lit up during Winter Wonders',
  'sapin-de-noel-grand-place-bruxelles': 'The lit Christmas tree in front of the Town Hall on the Grand-Place, Brussels',
  'gare-bruxelles-midi-quai-train': 'A high-speed train at the platform of Brussels-Midi station',
};

const NL: Record<string, string> = {
  'craves-hotel-bruxelles-chambre-velours-bleu': 'Kamer van Craves Hotel in Brussel: hoofdbord in blauw fluweel, rond kussen en ovale spiegel',
  'chambres-craves-hotel-bruxelles': 'Kamer van Craves Hotel met bloemenbehang, hoofdbord in blauw fluweel en plafondventilator',
  'chambre-simple-craves-bruxelles': 'Eenpersoonskamer van Craves Hotel met eenpersoonsbed, blauw fluweel en bloemenbehang',
  'chambre-simple-craves-bruxelles-2': 'Eenpersoonskamer van Craves Hotel, zicht op de deur en het hoofdbord',
  'chambre-simple-craves-salle-de-bains': 'Badkamer van de eenpersoonskamer met douche',
  'chambre-double-craves-bruxelles': 'Tweepersoonskamer van Craves Hotel: bed, hoofdbord in blauw fluweel en bloemenbehang',
  'chambre-double-craves-bruxelles-2': 'Tweepersoonskamer van Craves Hotel: groot bed, hoofdbord in blauw fluweel en bloemenbehang',
  'chambre-double-craves-detail': 'Kaptafel, oude lijsten en rode poef in de tweepersoonskamer',
  'chambre-double-craves-salle-de-bains': 'Badkamer van de tweepersoonskamer met bad en dubbele wastafel',
  'chambre-triple-craves-lit-double-et-simple': 'Driepersoonskamer van Craves Hotel met een tweepersoonsbed en een eenpersoonsbed',
  'chambre-triple-craves-banquette': 'Zitbank en rode poef in de driepersoonskamer',
  'chambre-triple-craves-service-the': 'Porseleinen theeservies op het marmer van de driepersoonskamer',
  'chambre-famille-craves-bruxelles': 'Familiekamer van Craves Hotel met zithoek en slaapbank',
  'chambre-famille-craves-portrait': 'Familiekamer van Craves Hotel met eethoek en zithoek',
  'chambre-famille-craves-chambre': 'Bedden van de familiekamer, bloemenbehang en fluwelen hoofdbord',
  'chambre-famille-craves-coin-repas': 'Kitchenette en eethoek van de familiekamer',
  'le-conteur-bar-restaurant-craves': 'De bar van restaurant Le Conteur, oranje krukken en rekken met flessen',
  'le-conteur-restaurant-craves-bruxelles': 'Gasten die klinken bij mezze in restaurant Le Conteur',
  'le-conteur-pain-tresse-mezze': 'Gevlochten sesambrood en mezze om te delen in Le Conteur',
  'le-conteur-cocktail-barman': 'Barman van Le Conteur die een cocktail met bessen inschenkt',
  'le-conteur-poisson-grille': 'Gegrilde vis geserveerd op een blauw aardewerken bord',
  'le-conteur-applique-laiton': 'Messing wandlamp op de witte tegels van Le Conteur',
  'le-conteur-diner-festif': 'Gasten die klinken met rode wijn aan een tafel in Le Conteur',
  'le-conteur-cocktail-ambre': 'Amberkleurige cocktail met gedroogde citroen en kaneel',
  'scene-bar-craves-bruxelles': 'De verlichte toog van bar Scène, op het Atrium-niveau van Craves',
  'scene-bar-enseigne-leopard': 'Uithangbord van Scène op een luipaardprint, rood licht',
  'scene-bar-cocktail-flambe': 'Geflambeerde cocktail geserveerd in een kleurrijke doodskop in bar Scène',
  'scene-bar-dj-soiree': 'Dj-avond in bar Scène',
  'scene-bar-neon': 'Rode neon aan de ingang van bar Scène',
  'scene-bar-lustres-soiree': 'De zaal van Scène onder de kroonluchters, privéfeest',
  'craves-reception-hall': 'De receptie van Craves Hotel, hout en warm licht',
  'craves-reception-accueil': 'De receptie van Craves Hotel, houten balie en rode fauteuil',
  'craves-couloir-moquette-florale': 'Gang van Craves Hotel, donker houtwerk en vloerbekleding met bloemmotief',
  'craves-couloir-bleu': 'Blauwe gang van Craves Hotel',
  'craves-papier-peint-floral': 'Bloemenbehang geïnspireerd op de vijf zintuigen',
  'craves-papier-peint-floral-2': 'Bloemenbehang van Craves',
  'craves-rideau-velours-embrasse-or': 'Blauw fluwelen gordijn met gouden embrasse',
  'craves-applique-lumiere': 'Wandlamp in geslepen glas en warm licht',
  'craves-telephone-retro': 'Retrotelefoon op het marmer van een kamer',
  'craves-tapis-motif': 'Tapijt met motief op parket',
  'craves-cocktail-marbre': 'Roze cocktail in een coupeglas op marmer',
  'palais-royal-bruxelles': 'Het Koninklijk Paleis van Brussel',
  'grand-place-bruxelles-crepuscule': 'De Grote Markt van Brussel bij schemering, op 4 minuten wandelen van Craves Hotel',
  'grand-place-bruxelles-hotel-de-ville': 'Het stadhuis op de Grote Markt van Brussel, op 4 minuten wandelen van Craves',
  'manneken-pis-bruxelles': 'Het standbeeld van Manneken Pis in Brussel',
  'palais-de-justice-bruxelles': 'Zuilen van het Justitiepaleis in Brussel',
  'plaisirs-d-hiver-grande-roue-bruxelles': 'Het verlichte reuzenrad van Winterpret in Brussel',
  'plaisirs-d-hiver-eglise-sainte-catherine': 'De verlichte Sint-Katelijnekerk tijdens Winterpret',
  'sapin-de-noel-grand-place-bruxelles': 'De verlichte kerstboom voor het stadhuis op de Grote Markt in Brussel',
  'gare-bruxelles-midi-quai-train': 'Een hogesnelheidstrein aan het perron van station Brussel-Zuid',
};

const ALTS: Localized<Record<string, string>> = { fr: FR, en: EN, nl: NL };

export function altFor(name: string, locale: Locale): string {
  const alt = pick(ALTS, locale)[name] ?? FR[name];
  if (alt === undefined) throw new Error(`Missing alt text for photo "${name}" in src/content/photos.ts`);
  return alt;
}
